Update to alpine:3.4

diff --git a/workspace-image/bin/install-docker b/workspace-image/bin/install-docker
--- a/workspace-image/bin/install-docker
+++ b/workspace-image/bin/install-docker
@@ -1,12 +1,28 @@
 #/bin/ash
 set -e
-docker_version="$1"
-if [ "$docker_version" == "" ];then
-    echo "Please provide a Docker version number as argument"
+
+if [ ! $1 ];then
+    echo "Please specify a Docker version"
     exit 1
 fi
+cd /tmp
 curl \
     --location \
-    --url https://get.docker.com/builds/Linux/x86_64/docker-$docker_version \
-    --output /usr/bin/docker-$docker_version && \
-chmod +x /usr/bin/docker-$docker_version
+    --url https://get.docker.com/builds/Linux/x86_64/docker-$1.tgz \
+    --output docker-$1.tgz
+
+if [ "$(file --mime-type docker-$1.tgz)" != "docker-$1.tgz: application/x-gzip" ];then
+    echo "Invalid docker version: $1"
+    exit 1
+fi
+tar -zxf ./docker-$1.tgz
+rm docker-$1.tgz
+mkdir -p /usr/lib/docker-bins
+if [ -f ./docker/docker ];then
+    mv ./docker/docker /usr/lib/docker-bins/docker-$1
+else
+    mv -f usr/local/bin/docker /usr/lib/docker-bins/docker-$1
+    rm -rf usr
+fi
+chmod +x /usr/lib/docker-bins/docker-$1
+/usr/lib/docker-bins/docker-$1 --version
